In [1]:
import numpy as np

In [2]:
# Vertörel türde bir array tanımlaması yapalım.

vector = np.array([10,20,30,40,50])

In [3]:
# içerde tanımlamasını yaptığım array içindeki değerleri index numaralarına göre çağırma işlemini yapıyorum.

vector[0]

10

In [4]:
vector[3]

40

In [5]:
# -1 olarak çağırdığım index aslında sonuncu index olarak bilinit bu python özelliğidir.

vector[-1]

50

In [6]:
# Belli bir aralığı çağıraçak ise yapmam gereken şu olmalıdır.

vector[2:4]

array([30, 40])

In [8]:
# Eğer ornek olarak ilk 3 elemanı çağırma işlemini yapmam gerekirse yapmam gereken aslında şu olmalıdır.

vector[:3]

array([10, 20, 30])

In [9]:
# Eğer belli bir sıra ile çağırmasını yaparsam yapmam gereken şu olmalıdır. ikişer ikişer gelmesini sağlıyorum.

vector[0:6:2]

array([10, 30, 50])