In [1]:
import numpy as np

In [2]:
# Bir vectörel array tanımlamasını yapıyorum.
# Bir matriks Olarak iki boyutlu bir array tanımlamasını yapıyorum.

vector = np.array([1,2,3])
matrix = np.array([[1,2,3],[1,2,3]])

In [4]:
# Tanımladığım arraylari ekrana yazdırıyorum.

print(vector)

[1 2 3]


In [5]:
print(matrix)

[[1 2 3]
 [1 2 3]]


In [6]:
# Yazmış olduğum dizilerin size yani büyüklüğünü buluıyorum.

vector.size

3

In [7]:
matrix.size

6

In [8]:
# şeklini yani 3 elemanlı bir değer tutan biçim olarak tanımlıyor.

vector.shape

(3,)

In [9]:
# Bu sefer iki boyutta 3 veri tutan bir biçim olarak tanımlıyor.

matrix.shape

(2, 3)

In [10]:
# ŞLimdi ise bu dizilerimin uzayda kapladığı alanı bakalım.

vector.ndim

1

In [11]:
# Bu örnektede görüldüğü gibi aslında matrix uzay zamanda iki boyutlu yer kaplıyor.

matrix.ndim

2

In [12]:
# Bu değerlerin veri şeklini veri türünü sorgulamak istersen yapmam gereken şu olmalıdır.

vector.dtype

dtype('int32')

In [13]:
matrix.dtype

dtype('int32')

In [ ]:
"""
Buradaki tek gerçek fark boyuttur. Buradaki int türlerinin tümü, değişen boyutlarda imzalı tamsayı değerleridir

Int16: 2 bayt
Int32ve int: 4 bayt
Int64: 8 bayt

Int64: Geri kalanıyla arasında küçük bir fark var . 
32 bitlik bir platformda, bir Int64depolama konumuna yapılan atamaların atomik olduğu garanti edilmez.
Diğer tüm türler için garantilidir.
"""

In [14]:
# numpy'da bir array olduğunu bize type vererek söylüyecektir.

type(vector)

numpy.ndarray

In [16]:
type(matrix)

numpy.ndarray