In [3]:
import numpy as np

In [4]:
matris = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [5]:
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [6]:
matris[0]

array([1, 2, 3, 4])

In [7]:
matris[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
# burda ise yaptığım 0. sütünda 1. ve 2. indexi almasını sağladım.

matris[0,:2]

array([1, 2])

In [9]:
# Şimdi ben daha farklı bir örnek ile anlatmaya çalışayım.
# virgülden önceki sütünları simgelerken virgülden sonrası satırları simgelemektedir.
# Aşağıdaki örnekte 0. sütün ile 1. indexleri almaya çalışacağım.

matris[0:4,0:1]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [14]:
# Şimdi ise 2. ve 3. sütünları ve bunların bütün sütünlarını almak istersem

matris[0:4,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [15]:
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
# Şimdi yukardan kopya çekerek 6,7 ve 10,11 değerlerini ekrana getirmeye çalışaçağım.

matris[1:3,1:3]

array([[ 6,  7],
       [10, 11]])