In [1]:
import numpy as np

In [2]:
# Ben eğer bir liste tanımlaması yapaçak olsam bunu tek tek yaparım eğer bir milyona kadar veri listenecek ise burda "arange" komutu devreye girer.

liste =[1,2,3,4,5,6,7]
range(1_000_000)

range(0, 1000000)

In [3]:
# Şimdi arange methodu üzerinden bunu yapmaya çalışalım.

milyon = np.arange(1_000_000)

In [4]:
milyon

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [5]:
# Şimdi ben burda 10'a kadar olan ama 10 dahil olmayan şeklinde olark listelenmesini yapıyorum.

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Bu işlemi 5 ile 10 arasında yapmak istersem.

np.arange(5,10)

array([5, 6, 7, 8, 9])

In [11]:
# Şimdi ise 1 ile 20 arasında 20 dahil değil ikişer ikişer getirmesini sağlıyorum.,

tek = np.arange(1,20,2)
cift = np.arange(0,20,2)
print("Tek olarak gelmesini istersem :", tek)
print("Çift olarak gelmesini istersem :", cift)

Tek olarak gelmesini istersem : [ 1  3  5  7  9 11 13 15 17 19]
Çift olarak gelmesini istersem : [ 0  2  4  6  8 10 12 14 16 18]
