In [1]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [5]:
# şimdi burada ise ben bu aralıkları kaça böleceğimi tanımlıyorum. Ve bunu "linspace" ile yapıyorum.
# 0 ile 20 arasını 12 parçaya dilimliyorum.
# Bi önemli nokta bu methotda son eleman dahildir.

np.linspace(0,20,12)

array([ 0.        ,  1.81818182,  3.63636364,  5.45454545,  7.27272727,
        9.09090909, 10.90909091, 12.72727273, 14.54545455, 16.36363636,
       18.18181818, 20.        ])

In [7]:
# İki aralık arasındaki değeri bulmak istersem.

bol = np.linspace(3,12,5)
bol

array([ 3.  ,  5.25,  7.5 ,  9.75, 12.  ])

In [8]:
# 2. index ile 1. index arasındaki değeri çıkarttımn.

bol[1]-bol[0]

2.25

In [11]:
# buralıklar eşittir. Hadi bakalım.

birinci_aralık = bol[1]-bol[0]
ikinci_aralık = bol[2]-bol[1]
ucuncu_aralık = bol[3]-bol[2]
dortuncu_aralık = bol[4]-bol[3]

print(birinci_aralık)
print(ikinci_aralık)
print(ucuncu_aralık)
print(dortuncu_aralık)


2.25
2.25
2.25
2.25
