In [1]:
import numpy as np

In [2]:
# Random değerlerle oluşan 4x4 boyutunda bir matris oluşturuyorum.

matris = np.random.randint(0,5,(4,4))

In [3]:
matris

array([[0, 1, 0, 3],
       [4, 2, 1, 1],
       [4, 4, 0, 1],
       [2, 1, 2, 0]])

In [4]:
# Şimdi view komutunu kullanarak burda var olan matrisi farklı bir değişkene atamasını yapıyorum.

matris2 = matris.view()

In [5]:
matris2

array([[0, 1, 0, 3],
       [4, 2, 1, 1],
       [4, 4, 0, 1],
       [2, 1, 2, 0]])

In [6]:
# Yukarda yaptığım işlem sonrasında şimdi bu teni değişkene bakalım.

matris2[0]

array([0, 1, 0, 3])

In [7]:
# Ben yukardaki elemanda 0. elemanı çağırıdm şimdi buna yeni atama yapmak istersen onu nasıl yapaçağım bakalım.

matris2[0] = [9,9,9,9]

In [8]:
# Yukardaki yaptığım değişikliğin etkisini burada görebilirim.

matris2

array([[9, 9, 9, 9],
       [4, 2, 1, 1],
       [4, 4, 0, 1],
       [2, 1, 2, 0]])

In [9]:
# Bu etki'yi ben matris değişkenimde'de görebilirim.
# Yani burada bu etki aslında iki değişkenede etki eder.

matris

array([[9, 9, 9, 9],
       [4, 2, 1, 1],
       [4, 4, 0, 1],
       [2, 1, 2, 0]])

In [10]:
# Şimdi random method'u ile yeni bir matris oluşturalım.

matris3 = np.random.randint(0,5,(4,4))

In [11]:
matris3

array([[3, 1, 2, 0],
       [4, 4, 0, 2],
       [3, 1, 1, 1],
       [4, 4, 3, 1]])

In [12]:
# Bu seher copy methodunu kullanıyorum.

matris4 = matris3.copy()

In [13]:
matris4[0] = [3,3,3,3]

In [14]:
matris4

array([[3, 3, 3, 3],
       [4, 4, 0, 2],
       [3, 1, 1, 1],
       [4, 4, 3, 1]])

In [15]:
# Bakın önemli nokta ben view methodunu kullandığımda burda matris aldığım değişkenede etki ediyor.
# Ama copy methodunu kullanırsam burda o değişkeni aldığım değişkene etki etmiyor.

matris3

array([[3, 1, 2, 0],
       [4, 4, 0, 2],
       [3, 1, 1, 1],
       [4, 4, 3, 1]])