In [1]:
import numpy as np

In [ ]:
# Ben eğer komplike matris oluşturacaksam bu bu komplike yapıları temel olarak oluşturmama yarayacak bazı yapılar vardır.

In [2]:
# İlk olarak "zeros" ile başlayalım.
# Eğer örneğime bakarsanız benim bir matrisi olan be içerisinde beş değer içeren bir yapı oluşturduğumu gösteriyor.

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
# Eğer ben 7x6yapılı bir matris yapısı oluşturmak istersem.

np.zeros((7,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
# Eğer ben bir vektörel bir yapı oluşturmak istersem.

np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [6]:
# Eğer ones parametresini kullanıp buna shape verirsem bir matris yapısı oluştururum.

np.ones(shape=(5,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
# Peki istediğim sayılardan yada istediğim şekle sahip olan bir matris oluşturmak istersem yapmam gereken ne olmalıdır.

np.full((5,5),12)

array([[12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12]])