In [1]:
import numpy as np

In [2]:
# Ben eğer oluşturduğum matriks'lere birer şekil vermek istersem yapmam gereken.
# Altaki örnek özelinde bakarsanız eğer sol baştan sağa alta uzanan bir 1 değerleri görürsünüz.

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
# Şimdi bu örüntüyü ötelemesini yapaılm.
# Bakın alttaki örnek özelinde örüntüyü 1. konumdan 2 konum sağ tarfa öteledim.

np.eye(5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
# Peki var var olan şekli ben fiziksel vermek istersem.,

np.diag([1,1,1,1,1])

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [6]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [7]:
# Bu "diag" komutu var olan bir köşegenide gatirebilir.

x = np.random.randint(0,3,(5,5))
print(x)

[[2 1 1 2 1]
 [0 1 2 2 2]
 [2 1 2 1 0]
 [0 2 0 2 1]
 [1 2 1 2 2]]


In [8]:
np.diag(x)

array([2, 1, 2, 2, 2])

In [9]:
# Peki köşegeni başka bir matriks'in köşegenine sahip olan başka bir matriks oluşturalım.

np.diag(np.diag(x))

array([[2, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 2]])