In [1]:
import numpy as np

In [5]:
m1 = np.ones((5,5))
m2 = np.full((5,5),12)

In [3]:
m1

# Ben "ones" ile oluşturduğum zaman float yapıda değer oluşur iken.

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
m2

# ben "full" ile değişken oluşturduğum zaman ise değer integer oluşuyor.

array([[12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12]])

In [8]:
# m1 değişkeninin burda yapısını değiştirmek istersem ise.

m1 = m1.astype("int8")
m1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [9]:
# Eğer ben 1'lerden oluşmasını değilde 5'lerden oluşmasını istersem ise.

m1*5

# Bu çarpma işleminde vektörel bir çarpma yapıyor aynı anda bir çok veriyi çarpıyor.

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]], dtype=int8)

In [11]:
# Eğer matriks'de var olan değerleri toplama işlemi yaptırmak istersem ne yapmak zorundayım.

m2+3

# Şeklinde yaparım.

array([[15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15]])

In [12]:
# Peki ben var olan iki matriksi toplayabilirmiyim?

m1+m2

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [13]:
m2-m1

array([[11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11]])

In [14]:
# Matriks'lerde bölme işlemide yapabilirim.

m2/5

array([[2.4, 2.4, 2.4, 2.4, 2.4],
       [2.4, 2.4, 2.4, 2.4, 2.4],
       [2.4, 2.4, 2.4, 2.4, 2.4],
       [2.4, 2.4, 2.4, 2.4, 2.4],
       [2.4, 2.4, 2.4, 2.4, 2.4]])

In [15]:
# Eğer matriksi tam sayı olark yazdırmak istersem.

m2//5

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]], dtype=int32)

In [16]:
# Eğer mod hesaplaması yaptırmak istersem yapmam gereken şu olmalıdır.

m2%5

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]], dtype=int32)

In [18]:
m3 = np.full((5,6),3)
m3

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [19]:
m3.shape

(5, 6)

In [21]:
m1.shape

(5, 5)

In [22]:
# Yukarda gördünüz yapıları farklı iki matriks toplayabilirmi?

m3+m1

# hayıt hata veriri.

ValueError: operands could not be broadcast together with shapes (5,6) (5,5) 

In [26]:
# Peki bunların var olan durumuna göre toplamasını sağlarsam nasıl olmalıdır.

# Öncelikle fazla karakteri olan değeri bir alalım be bunu az karakteri olan değer kadar almasını istiyelim.

m3_1 = m3.reshape(30)[:25].reshape(5,5)
# İlk 25 karakterini almasını sağladım ve sonra bunu 5x5 lik matrikse cevirdim.
m3_1

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [27]:
# Artık toplama yaptırabilirim.

m3_1+m1

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [28]:
# m1 değişkenimin ilk satırını 3 ile çarpasam.

m1[0]*3

array([3, 3, 3, 3, 3], dtype=int8)

In [30]:
# Yukardaki işlemi eğer m1 değişkeninin içine kaydetmek istersem yapmam gereken şu olmalıdır.

m1[0] = m1[0]*3
m1

array([[9, 9, 9, 9, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [ ]:
# Ben eğer yukardaki gibi 5x5 lik bir matriks ile 5 değeri olan verktorel bir kavramla çarpabilirim bunu o satırlarla sırayla çarparak olur.

In [31]:
m1

array([[9, 9, 9, 9, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [33]:
m4 = np.arange(5).reshape((5,1))
m4

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [34]:
# şimidi 5x5 lik bir matriks ile 5 değeri olan vektörel bir kavramı çarpaçağım.

m1*m4

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [35]:
# Dikey boyutta uyuştuğu için toplamada yapabilirim.

m1+m4

array([[9, 9, 9, 9, 9],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]])

In [36]:
# Yine dikeydeki bnzerlikten yararlandım ve bunların bölünmesini sağladım.

m4/m1

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [38]:
# Ben istersem 5x5 lik bir batriksinde verktörel olarak 5 lik olaçağı için onuda çarpa bilirim.

m1*np.diag(m1)

array([[81,  9,  9,  9,  9],
       [ 9,  1,  1,  1,  1],
       [ 9,  1,  1,  1,  1],
       [ 9,  1,  1,  1,  1],
       [ 9,  1,  1,  1,  1]], dtype=int8)