In [1]:
import numpy as np

In [2]:
matris = np.random.randint(0,10,(5,5))

In [3]:
matris

array([[0, 3, 8, 1, 8],
       [8, 6, 6, 1, 5],
       [4, 5, 5, 7, 2],
       [6, 0, 1, 4, 5],
       [0, 3, 0, 5, 6]])

In [4]:
# burada mantıksal bir işlem yaptırmak istiyorum ve 5'den büyük olanları bana true yada false döndürmesini istiyorum.

matris>5

array([[False, False,  True, False,  True],
       [ True,  True,  True, False, False],
       [False, False, False,  True, False],
       [ True, False, False, False, False],
       [False, False, False, False,  True]])

In [5]:
# Büyük olan değerleri bana geritmesini istiyorsam eğer.

matris[matris>5]

array([8, 8, 8, 6, 6, 7, 6, 6])

In [6]:
matris[matris<5]

array([0, 3, 1, 1, 4, 2, 0, 1, 4, 0, 3, 0])

In [7]:
matris[matris>=5]

array([8, 8, 8, 6, 6, 5, 5, 5, 7, 6, 5, 5, 6])

In [8]:
matris[matris==5]

array([5, 5, 5, 5, 5])

In [9]:
# şimdi bu değler kaç tane ona bakalım.

matris[matris==5].size

5

In [10]:
# Şimdi 7'ye eşit olmayan değerlere bakalım.

matris[matris!=7]

array([0, 3, 8, 1, 8, 8, 6, 6, 1, 5, 4, 5, 5, 2, 6, 0, 1, 4, 5, 0, 3, 0,
       5, 6])

In [11]:
# Yukardaki değerler kaç tane.

matris[matris!=7].size

24

In [12]:
# Şimdi birbirini tekrar eden sayı varmı ona bakalım.

matris%2==0

array([[ True, False,  True, False,  True],
       [ True,  True,  True, False, False],
       [ True, False, False, False,  True],
       [ True,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [13]:
# Peki bu tekrar eden sayılar hangileir.

matris[matris%2==0]

array([0, 8, 8, 8, 6, 6, 4, 2, 6, 0, 4, 0, 0, 6])

In [21]:
# Şimdi ben sıfıra eşit olmayan çift sayıları getir diyorum.

sifir = matris!=0
cift = matris%2==0
bir = matris == 1

In [19]:
matris[cift & sifir]

array([8, 8, 8, 6, 6, 4, 2, 6, 4, 6])

In [22]:
# Şimdi ise çift veya 1 olan sayıları bul

matris[cift | bir]

array([0, 8, 1, 8, 8, 6, 6, 1, 4, 2, 6, 0, 1, 4, 0, 0, 6])

In [23]:
# Şimdi ben çift olacak ama sıfır olmayacak veya 1 olacak desem şu şekil olur.

matris[(cift & sifir) | bir]

array([8, 1, 8, 8, 6, 6, 1, 4, 2, 6, 1, 4, 6])

In [28]:
# Ben bu koşulu başka bir matris yapısı içinde kullanabilirim.

matris2 = np.full((5,5),5)

In [30]:
matris2

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [31]:
matris2[(cift & sifir) | bir]

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])